-- File generated by the BNF Converter (bnfc 2.9.6.1).

{-# LANGUAGE DeriveDataTypeable #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language LF2.

module AbsLF where

import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

import qualified Data.Data    as C (Data)
import qualified GHC.Generics as C (Generic)

data Program = Prog [Function]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Generic)

data Function = Fun Type Ident [Decl] Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Generic)

data Decl = Dec Type Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Generic)

data Exp
    = EIf Exp Exp Exp
    | EOr Exp Exp
    | EAnd Exp Exp
    | ENot Exp
    | ECon Exp Exp
    | EAdd Exp Exp
    | ESub Exp Exp
    | EMul Exp Exp
    | EDiv Exp Exp
    | ECall Ident [Exp]
    | EInt Integer
    | EVar Ident
    | EStr String
    | ETrue
    | EFalse
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Generic)

data Type = Tbool | Tint | TStr | TFun Type [Type]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Generic)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Generic, Data.String.IsString)

